name: flutter_image_progression
description: Progression widget with a list of images with different steps drawn on top of eachother.
version: 0.0.1

repository: https://github.com/Iconica-Development/flutter_image_progression
issue_tracker: https://github.com/Iconica-Development/flutter_image_progression/issues

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
